// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bmO3lm_JInWVcoLJvqiY0Jfhemb8DoQ',
    appId: '1:407561111254:web:4303c90325ab757bf4ab77',
    messagingSenderId: '407561111254',
    projectId: 'pager-chat-d7928',
    authDomain: 'pager-chat-d7928.firebaseapp.com',
    storageBucket: 'pager-chat-d7928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6pwN7V7eWMFoH0MmCHk7fw6R447m-Wv4',
    appId: '1:407561111254:android:1f438b9038e157b7f4ab77',
    messagingSenderId: '407561111254',
    projectId: 'pager-chat-d7928',
    storageBucket: 'pager-chat-d7928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHTs9FQIx7TE6nJxOydffCj61T8TBQVSM',
    appId: '1:407561111254:ios:e14599987b4392c4f4ab77',
    messagingSenderId: '407561111254',
    projectId: 'pager-chat-d7928',
    storageBucket: 'pager-chat-d7928.firebasestorage.app',
    iosBundleId: 'com.example.pagerChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHTs9FQIx7TE6nJxOydffCj61T8TBQVSM',
    appId: '1:407561111254:ios:e14599987b4392c4f4ab77',
    messagingSenderId: '407561111254',
    projectId: 'pager-chat-d7928',
    storageBucket: 'pager-chat-d7928.firebasestorage.app',
    iosBundleId: 'com.example.pagerChat',
  );
}
